# Copyright (C) 2018-2019 Lienol
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-adguardhome
LUCI_TITLE:=LuCI support for adguardhome
PKG_DEPENDS:=+!wget&&!curl:wget
LUCI_PKGARCH:=all
PKG_VERSION:=1.8
PKG_RELEASE:=20200824
PKG_MAINTAINER:=<https://github.com/rufengsuixing/luci-app-adguardhome>

include $(TOPDIR)/feeds/luci/luci.mk
